### ISSUE TITLE
can't parse correctly "EEE MMM dd HH:mm:ss z yyyy"

### ISSUE THREAD

**Issue by maifeeulasad** [felixge/node-dateformat#100]
If I simply try to parse date in `EEE MMM dd HH:mm:ss z yyyy` format, it gives something which is not date.
`dateFormat(Date.now(), "EEE MMM dd HH:mm:ss z yyyy")`

It returns **EEE 3737 04 21:01:08 z 2020**

[codesandbox.io](https://codesandbox.io/embed/heuristic-dew-jtwmj?fontsize=14&hidenavigation=1&theme=dark)

**Comment by chase-manning** [comment]
@maifeeulasad  `EEE` is not a valid mask.  
See the [readme](https://github.com/felixge/node-dateformat) for a list of valid masks.
