### ISSUE TITLE
how to get wednesday september 2nd 2020 to new Date() or 09/02/2020

### ISSUE THREAD

**Issue by dipanjanpanja6** [felixge/node-dateformat#105]
in my database i have date in this format => Wednesday, September 2nd, 2020 which i get form npm dateformat dateFormat(new Date(),"dddd, mmmm dS, yyyy, h:MM:ss TT").

now i need to sort all date by descending order and change structure to like 9/2/2020 but new Date("Wednesday, September 2nd, 2020") throw an error because of 2nd its required only 2 or 02.

**Comment by chase-manning** [comment]
@dipanjanpanja6 It is always better to store the raw date format in your database and not the formatted version.  
I suggest changing your database to be in this format and then your life is easy :smile:  
Regardless I will be closing this issue as it outside of the scope of this library.
