### ISSUE TITLE
Breaking changes in v4.0.0?

### ISSUE THREAD

**Issue by Favna** [felixge/node-dateformat#132]
Hi there, I see you have released version 4.0.0. Could you document any breaking changes that are in this release either through GitHub releases or somewhere else?

**Comment by chase-manning** [comment]
Thanks @Favna ! I have added a [release](https://github.com/felixge/node-dateformat/releases/tag/v4.0.0) for this so you can read about the changes.  
I can confirm that there are no breaking changes in this release 😄
