### ISSUE TITLE
Invalid dates generating for "MM-dd-yyyy'T'HH:mm:ssZ"

### ISSUE THREAD

**Issue by aniltallam** [felixge/node-dateformat#164]
```
var dateFormat = require("dateformat");
var date = new Date(1630004827000) // 2021-08-26T19:07:07.000Z

console.log(dateFormat(date, "MM-dd-yyyy'T'HH:mm:ssZ")) // prints '37-27-2021T00:08:07GMT+0530'
```

node-dateformat npm module version: 4.5.1

**Comment by gumbol** [comment]
hi
try 
`console.log(dateFormat(date, "UTC:mm-dd-yyyy'T'HH:MM:ssZ"))`

lowercase m is for months where is uppercase M is for minutes. appending utc to the string converts time to the desired zone.

**Comment by chase-manning** [comment]
Closing as the issue should now be resolved.
