### ISSUE TITLE
4.6.1 causes broken ESM imports

### ISSUE THREAD

**Issue by csvan** [felixge/node-dateformat#167]
See https://github.com/yeoman/environment/issues/326

Seems like latest version no longer supports `require`

**Comment by chase-manning** [comment]
@csvan  Thanks, will fix now

**Comment by chase-manning** [comment]
@csvan  Fixed in version `4.6.2` of `dateformat` package:
https://www.npmjs.com/package/dateformat

**Comment by csvan** [comment]
Thanks!

**Comment by chase-manning** [comment]
@csvan  Actually, sorry use `v4.6.3` 😄

**Comment by hanshino** [comment]
Seems like same issue on `v5.0.1`.
No more support `require` ? Then I need find other solution..
