### ISSUE TITLE
Breaking change in 4.6.1

### ISSUE THREAD

**Issue by ardatan** [felixge/node-dateformat#168]
https://github.com/ardatan/graphql-tools/pull/3550
I think you accidentially pushed an ESM-only release as 4.6.1. So even if it is a minor release, it has a breaking change that drops CJS.

**Comment by chase-manning** [comment]
@ardatan  You're right I did sorry, it has been fixed now in version `4.6.3`, if you update to that should resolve the issue 😄

**Comment by ardatan** [comment]
Thank you for this project and also for quick response!

**Comment by chase-manning** [comment]
❤️
