### ISSUE TITLE
Time seems to off by 30 minutes

### ISSUE THREAD

**Issue by raul1991** [felixge/node-dateformat#181]
![image](https://user-images.githubusercontent.com/1281636/153539737-9fcce165-5eee-4265-9660-6eccd5e83894.png)

# Inputs
1644552380299 (UTC timezone)

# Expected
'2/11/2022, **9:36:20** AM'

# Actual
'Feb 11, 2022, **9:02am**GMT+0530'

# Version used
4.0.0

**Comment by Choyeongdeok** [comment]
maybe you should use MM(uppercase) not mm(lowercase)

**Comment by raul1991** [comment]
Yeah that was the problem. I forgot to update here.

**Comment by chase-manning** [comment]
Thanks @Choyeongdeok  🙏🏻
