### ISSUE TITLE
Add "tick" option to provide continuous output

### ISSUE THREAD

**Issue by rikkertkoppes** [felixge/node-dateformat#29]
I am interested in having a ticking clock command line utility, to be able to pipe it into other things.

Would you be interested in having it added to node-dateformat? If so, I am willing to contribute a pull request. Otherwise, I'll probably create a new package based on node-dateformat.

I was thinking along the lines of

    dateformat "HH:MM:ss" -t 
    dateformat "HH:MM:ss" -t 5s
    dateformat "HH:MM:ss" -t 1m

to tick every second, 5 seconds and minute.

**Comment by ctavan** [comment]
Hi @rikkertkoppes . I think this is out of scope for node-dateformat and should be supplied as a stand-alone module. However of course feel free to use node-dateformat internally!

**Comment by rikkertkoppes** [comment]
For reference: https://github.com/FirstLegoLeague/cli-time
