### ISSUE TITLE
[Fork & Pull request]: adding localisation information to date formatter

### ISSUE THREAD

**Issue by murdockcrc** [felixge/node-dateformat#31]
I've come across this lib and observed that all days/months strings are in English. I would like to propose extending this lib to accommodate strings in other languages. If the repo maintainers agree to this change, I'd be happy to fork the repo and implement the change for a pull consideration.

**Comment by ctavan** [comment]
@murdockcrc I recommend taking a look at http://momentjs.com/ for a fully internationalized date+time library. Feel free to reopen this issue if moment.js doesn't work for you.
