### ISSUE TITLE
Formatting day from string returns the day before.

### ISSUE THREAD

**Issue by Raizunne** [felixge/node-dateformat#34]
Im trying to format the date from:
2015-05-02
which should return May 2nd, 2015 but im getting May 1, 2015.

**Comment by maxtherocket** [comment]
I'm getting the same issue

dateformat "2015-12-18" "dd mm yyyy"
-> 17 12 2015

**Comment by jimgiven** [comment]
I just had the same problem, looks like the answer is [here](https://github.com/felixge/node-dateformat/issues/22)

**Comment by nwhitmont** [comment]
same issue here in UTC-7 (PST)

@jimgiven can you provide a code sample showing where and how you set the `utc=true` property? Thanks!

**Comment by bondarewicz** [comment]
@nwhitmont `dateFormat(now, "longTime", true);` from docs:
```
// And finally, you can convert local time to UTC time. Simply pass in
// true as an additional argument (no argument skipping allowed in this case):
dateFormat(now, "longTime", true);
// 10:46:21 PM UTC
```

**Comment by jimgiven** [comment]
Thanks @bondarewicz! It was too long for me to remember.

**Comment by pmkay** [comment]
adding a third argument helped to parse my date only values correctly. in my case //example '2017-06-19' with `dateFormat(date, "dddd, mmmm dS")` would parse incorrectly to Sunday June 18th. With third argument -> `dateFormat(date, "dddd, mmmm dS", true)`  conversion was made to 19th of June correctly as @bondarewicz mentioned. This issue should be closed

**Comment by chase-manning** [comment]
Closing as this has now been resolved
