### ISSUE TITLE
Uncaught TypeError: Invalid date

### ISSUE THREAD

**Issue by alioygur** [felixge/node-dateformat#35]
I am using this package with webpack on browser side. 

I am using it like this.

```
var formatDate = require('dateformat'); 
```

but I am getting this error. "Uncaught TypeError: Invalid date"

notice that, I am getting this error even when not use.

I think this problem about [this line](https://github.com/felixge/node-dateformat/blob/master/lib/dateformat.js#L217)

**Comment by bigsassy** [comment]
I'm getting the same error.  It worked fine when using Browserify, but since switching to webpack I've been experiencing this same error.  Happens when importing the library, not actually calling it on a date string.

**Comment by clns** [comment]
Same here.

**Comment by rubenhazelaar** [comment]
I still have the same issue even though I pulled from the master branch from github through NPM. The following line of code on line 4 of my code results in "Uncaught TypeError: Invalid date":

     var dateFormat = require('dateformat');

A stacktrace

    line 4: [myfile.js]
    line 224: dateformat.js
    line 218: dateformat.js
    line 39: dateformat.js

BTW, I'm using Webpack

**Comment by rey-wright** [comment]
+1. I'm getting the exact same error using Webpack.

**Comment by iNikNik** [comment]
+1. Same ... with webpack

**Comment by jheander** [comment]
+1, webpack

**Comment by jheander** [comment]
I have now published a new npm package "dateformat-light" that removes the CLI, and fixes the AMD inclusion bug

**Comment by iNikNik** [comment]
@jheander that's nice! thx)

**Comment by praveenax** [comment]
dataformat-light worked out with webpack :+1:

**Comment by usirin** [comment]
incase anyone still requires to run `dateformat` in `webpack` you can use `imports-loader` to force `define` to be `false` therefore make it run as `common.js` module:

```
{
  module: {
    loaders: [
      { test: /dateformat/, loader: 'imports?define=>false' }
    ]
  }
}
```

**Comment by reywright** [comment]
@jheander thanks, saw your comment and I've been using it for a couple of months.

**Comment by ddeath** [comment]
Working on chrome with webpack but not in firefox. In firefox same error.

**Comment by chase-manning** [comment]
Closing as this is resolved now

**Comment by Dr-Nikson** [comment]
@chase-manning thanks!
