### ISSUE TITLE
Please pad years before the year 1000

### ISSUE THREAD

**Issue by jjiadev** [felixge/node-dateformat#39]
Currently when attempting to format the year of any year before the year 1000, you end up with a less than ideal looking string.

IE: 0012/06/24 will become 12/06/24, which does not fit into a html date input field. Can you please pad zeroes out for any year before the 1000 to avoid this issue?

**Comment by rekhubs** [comment]
Why is this still not merged?!
I met the same problem on Chrome Version 84.0.4147.135 (Official Build) (64-bit). I wish to have this fixed.

**Comment by federico-bellucci** [comment]
Is there a way to avoid this?
I need to format dates for a chronology application and the year padding looks ugly. 
For instance, if I use `dateFormat('0020-11-02', 'mmmm yyyy')` I get `November 0020` which is not what I want. 
Is there a way to automatically handle it? Or do I need to pass the right amount of `y`s?
