### ISSUE TITLE
Issue on passing normal text to dateFormat function

### ISSUE THREAD

**Issue by brunokrebs** [felixge/node-dateformat#42]
As per README.md description the following code should work:

```
// ...Or add your own
dateFormat.masks.hammerTime = 'HH:MM! "Can\'t touch this!"';
dateFormat(now, "hammerTime");
// 17:46! Can't touch this!
```

But, as I have seen in my app, it does not. So I figured it out that I have to pass the desired text nested in the same type of quote (single ' or double "), with backward slashes, as the one the nests the format it self.

Example given (double quotes):

```
// Now this works
dateFormat.masks.hammerTime = "HH:MM! \"Can't touch this!\"";
dateFormat(now, "hammerTime");
// 17:46! Can't touch this!
```

So, I have no idea if I'm doing something wrong, but if this is true a real issue that I see is that would be impossible to pass the word can't as normal text when using single quotes...

**Comment by thunderkid** [comment]
I got this too. Without your workaround the letter t of can't is interpreted as an am/pm formatting code. Thanks for the tip.

**Comment by mlukasiak** [comment]
In my case it worked when I switched ' with ".  "HH:MM! 'Can\'t touch this!'" works fine.

**Comment by DarrenCook** [comment]
I was about to report this bug too. Single quotes works as described in the documentation, but double quotes does not.  E.g. `'mmmm "to" mm'` gives `March \"p+0100\" 03`  whereas `"mmmm 'to' mm"` gives the expected `March to 03`

**Comment by rivertam** [comment]
This is still an issue. I'd be happy to submit a pull request fixing it, but I'm not sure how the library would prefer to do things.

**Comment by chase-manning** [comment]
Closing this issue as this looks to be resolved now.  
If you can still replicate the issue please let me know
