### ISSUE TITLE
dateformat library throws uncaught error when invalid date string is passed in

### ISSUE THREAD

**Issue by Marak** [felixge/node-dateformat#45]
Had a process exit unexpectedly today due to a malformed date string.

I understand why `dateformat` choose this API ( throwing an error ), because it's logical. What was not so nice, was having the process exit.

If anyone else hits this issue and is looking for a solution, you can simply create a wrapper method for `dateformat` with try / catch that returns a string ( instead of throwing an error ).

``` js


var df = require('dateformat');

var safeDf = function safeDf (str) {
  var res = '';
  try  {
    res = df(str);
  } catch (err) {
    res = "NaN";
  }
  return res;
};

```

**Comment by chase-manning** [comment]
@Marak  Thanks for raising this issue!  
I'm closing it for now as this is old, but please feel free to create a PR with any proposed changes around this.
