### ISSUE TITLE
How to parse a formatString into Date using this lib

### ISSUE THREAD

**Issue by yuhai1023** [felixge/node-dateformat#51]

**Comment by peteratticusberg** [comment]
+1 for the ability to reverse engineer a date from a string. 

Looked over the source, looks like this would be a non-trivial addition. Would consider putting up a PR for this if there was support.

**Comment by jonschlinkert** [comment]
Seems like this goes beyond the scope of this library. there are other node.js libs that do this.

**Comment by chase-manning** [comment]
Closing issue as this is agreed to be out of scope
