### ISSUE TITLE
Formatted date with starting and ending double quote

### ISSUE THREAD

**Issue by amitguptagwl** [felixge/node-dateformat#55]
When I call dateFormat(new Date('2016-07-31'), "dd mmmm, yyyy") it returns string : "31 July, 2016" with length 15 which means 2 starting and double quotes are the part of the result string.

**Comment by WORMSS** [comment]
```javascript
var result = dateformat(new Date('2016-07-31'), "dd mmmm, yyyy");
console.log(`Result: '${result}' length: ${result.length}`); // Result: '31 July, 2016' length: 13
```

No double quotes.

**Comment by mMontu** [comment]
The test @WORMSS  indicated also worked fine here.

**Comment by chase-manning** [comment]
Closing as this looks to not be an issue
