### ISSUE TITLE
TypeError: Invalid date (version 1.0.12) on Google Cloud Platform

### ISSUE THREAD

**Issue by cpup22** [felixge/node-dateformat#59]
I'm using dateformat for a custom node module deployed on Google Cloud Platform. 

code similar to:
`dateFormat(new Date().getTime(), "dddd, mmmm dS yyyy, h:MM TT");
`
And getting a "TypeError: Invalid date) error.  Here's the trace:

```
trying to do a dateFormat for timestamp: 1481054683108
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Invalid date
    at TypeError (native)
    at /opt/bitnami/apps/myapp/node_modules/dateformat/lib/dateformat.js:39:17
```

I believe the issue has something to do with the timestamp.  Because when I run outside of GCP on my local machine I also get the TypeError.

dateformat 1481054683108, "dddd, mmmm dS yyyy, h:MM TT"

but that timestamp seems okay (it's off from now but that's a different issue).  Any other reason why I would be seeing this error?  Running the same code locally works just fine (same versions of dateformat requirement), but the timestamp is a different value than what is created on the server...

**Comment by cpup22** [comment]
figured out my issue, Mongo was saving the value as a String not a Date.

**Comment by jonschlinkert** [comment]
thanks, can we close the issue then?
