### ISSUE TITLE
Timezone conversion and custom named formats

### ISSUE THREAD

**Issue by Tomino2112** [felixge/node-dateformat#65]
So far this library is working great for us, two improvements I'd like to suggest:

1) **Allow changing timezone** - We have one date that we need to display formatted in couple of timezones, would be great if that could be achieved directly with this library

2) **Custom named formats** - Would be great if you could specify your own named formats. For example the `fullDate` is great, but we need same just without the commas. Sure we can achieve it otherwise, but specifying our own custom named  formats would be a big bonus

**Comment by chase-manning** [comment]
@Tomino2112  Thanks for the feedback!

### 1.
Thanks for this suggestion, I will create a seperate issue for this.

### 2.
This now exists
```
// ...Or add your own
dateFormat.masks.hammerTime = 'HH:MM! "Can\'t touch this!"';
dateFormat(now, "hammerTime");
// 17:46! Can't touch this!
```
