### ISSUE TITLE
Getting Wrong out-put

### ISSUE THREAD

**Issue by schaitu** [felixge/node-dateformat#70]
Input:
`var nowDateYMD = dateformat('2016-01-12', 'mm-dd-yyyy');`
Output Date: 
`01-11-2016` // giving wrong date, showing one day less

Kindly do need full.

Thanks.

**Comment by willenglishiv** [comment]
I can report the same problem. dateFormat("2017-04-17", 'isoDate' ) comes out with "2017-04-16"

**Comment by wmelton** [comment]
Can confirm this is still an issue. 

@felixge - is this repo abandoned?

**Comment by wmelton** [comment]
All - issue is with the input format. You must pass in a full ISO8601 valid date. 

```
let date = new Date('2016-01-12'); //Invalid
let date = new Date('2016-01-12T00:00:00'); //Valid
```

@schaitu - this issue should probably be closed.

**Comment by chase-manning** [comment]
Closing issue as is user error
