### ISSUE TITLE
get a wrong minute!

### ISSUE THREAD

**Issue by senlin-wei** [felixge/node-dateformat#72]
Show info:
> dateformat('2016-01-12', 'mm-dd-yyyy hh:mm:ss')
'01-12-2016 08:01:00'
> dateformat(new Date(), 'yyyy年mm月dd日 HH:mm')
'2017年08月15日 14:08'
> new Date()
2017-08-15T06:00:47.027Z

**Comment by MrHayato** [comment]
`mm` is month, `MM` is minutes. You should be doing `HH:MM`

**Comment by chase-manning** [comment]
Closing as this is user error
