### ISSUE TITLE
isodatetime issue

### ISSUE THREAD

**Issue by monukanyal** [felixge/node-dateformat#76]
Hello, 

I am converting date '31 Mar 2017' to '2017-03-31T00:00:00'. I found solution as per your documentation: dateFormat(now, "isoDateTime"); 
so when i am using this :dateFormat('31 Mar 2017', "isoDateTime"); 
it is giving me output like:2017-03-31T00:00:00+0530
but i don't want +0530 part with datetime. please provide me the solution asap.

**Comment by taoqf** [comment]
I has the same problem

**Comment by doowb** [comment]
You can specify your own pattern instead of using `isoDateTime`:

```js
console.log(dateformat('31 Mar 2017', "yyyy-mm-dd'T'HH:MM:ss"));
```

**Comment by taoqf** [comment]
thanks
