### ISSUE TITLE
2.1.0 package not found in the registry

### ISSUE THREAD

**Issue by glucazeau** [felixge/node-dateformat#77]
Hello,

Is that normal that 2.1.0 is listed here https://registry.npmjs.org/dateformat but that the tarball is not available? https://registry.npmjs.org/dateformat/-/dateformat-2.1.0.tgz returns a 404.

I'm not used to NPM at all so I apologize if it's just a matter of time, related to some cache or whatever.

Thank you

**Comment by fpintos** [comment]
I've created the 2.1.0 release but then I realized the fix for the AM/PM string turned out to be a breaking change for those using the localized strings, so I've bumped the version to 3.0.0 to indicate that fact and published that one.

**Comment by glucazeau** [comment]
Thank you Fabio for your quick answer :)

Isn't it possible to unpublish it? Or at least put a message in the [release](https://github.com/felixge/node-dateformat/releases/tag/2.1.0) to explain that?

Two people here discovered this because dateformat is a transitive dependency from some project that seems to search for the latest 2.x. We first thought it was an issue with our private Sinopia before discovering that the package was actually missing on the public repository.

**Comment by fpintos** [comment]
Thanks for reporting. I ran unpublish, but it sounds like that still leaves some traces of its existence behind.
I've published a 2.2.0 with the previous version to keep 2.x references happy and then another 3.0 to bring that back to latest.
Lesson learned...
