### ISSUE TITLE
invalid '1970-01-01' date formatting 

### ISSUE THREAD

**Issue by djamaco** [felixge/node-dateformat#79]
I have a problem with '1970-01-01' date passing it like unix time stamp 
```javascript
const dateformat = require('dateformat');

const parsedDate = Date.parse('1970-01-01'); // will be 0
const formattedDate = dateformat(parsedDate, 'yyyy-mm-dd'); // will be current date instead of '1970-01-01'
```
here (https://github.com/felixge/node-dateformat/blob/master/lib/dateformat.js#L32) if 0 then it becomes current Date

**Comment by jheander** [comment]
Fixed in https://www.npmjs.com/package/dateformat-light/v/1.3.1
