### ISSUE TITLE
Did isoDateTime example string error at README.md?

### ISSUE THREAD

**Issue by ning-www** [felixge/node-dateformat#81]
https://github.com/felixge/node-dateformat#named-formats

One isoDateTime parameters are used here, and the result is what I expected.
dateFormat(now, "isoDateTime")  //2017-11-27T18:58:22+0800 

But, at README.md isoDateTime example no time zone suffix string.

Thanks!

**Comment by padraigfl** [comment]
isoDateTime's actual output is `yyyy-mm-dd\'T\'HH:MM:sso` as seen [here](https://github.com/felixge/node-dateformat/blob/c7fb1bc73fd1180df0b9670e83796ea14963298d/lib/dateformat.js#L118).

I imagine updating the readme makes more sense than potentially breaking implementations for people by changing the code? @felixge
