### ISSUE TITLE
Invalid parsed date

### ISSUE THREAD

**Issue by hugobarona** [felixge/node-dateformat#82]
Hi there, i tried dateformat via browser and locally in a js script, and the basic test was to instantiate a new date (1st Feb 2018). After providing the parameters as required, i get 1st Mar 2018. The month label is wrong.

![capture](https://user-images.githubusercontent.com/5125006/35725343-f86c0eca-07f8-11e8-9c36-8aeef9ea2fca.JPG)
Snapshot as attachment.

**Comment by doowb** [comment]
@hugobarona take a look at [this Date documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). The month argument is `0` based, so passing in `2` will give you the 3rd month.

**Comment by hugobarona** [comment]
I considered that but since the other parameters (day) start with 1, i thought it could be an invalid configuration. anyway, thanks.
