### ISSUE TITLE
Provide PDF date format

### ISSUE THREAD

**Issue by akaleeroy** [felixge/node-dateformat#83]
For PDF metadata fields `CreationDate` and `ModDate`

Format: `(D:YYYYMMDDHHmmSSOHH'mm')`

where

**YYYY** is the year
**MM** is the month
**DD** is the day (01-31)
**HH** is the hour (00-23)
**mm** is the minute (00-59)
**SS** is the second (00-59)
**O** is the relationship of local time to Universal Time (UT), denoted by one of the characters +, -, or Z 
**HH** followed by ' is the absolute value of the offset from UT in hours (00-23)
**mm** followed by ' is the absolute value of the offset from UT in minutes (00-59)

**Comment by chase-manning** [comment]
@akaleeroy Hi there, thanks so much for creating this issue!! 😄   
Sorry this was not looked at sooner, the repo was not under active maintenance at the time.  

After reviewing this suggestion, I think it is best that this is not implemented.  
The reason for this is that dateFormat is aimed at being a generic toolkit for users to create their own custom date formats.  
the PDF Metadata Fields are too specific to fall within the scope of this project.  
As if we were to include this format, then it would extend the scope of dateFormat to including the date format of all metadata fields for all software and standards which would be messy and unrealistic.  

If you do require regular use of a mask like this, you can create your own custom one in your project! 😄 
```
// ...Or add your own
dateFormat.masks.hammerTime = 'HH:MM! "Can\'t touch this!"';
dateFormat(now, "hammerTime");
// 17:46! Can't touch this!
```
