### ISSUE TITLE
Two digit milliseconds L sometimes returns three digits

### ISSUE THREAD

**Issue by ericnordebaeck** [felixge/node-dateformat#89]
I have a dateformat string that uses `L`, which should return milliseconds with 2 digits. The full dateformat string is `yyyymmddHHMMssL`, which should generate a 16 digit string that is then followed by other data - it's used for a filename generator.

I have a unit test doing a sanity check on this, which checks the presence of 16 digits using regexp.

Once in a blue moon this test fails because the resulting date format string contains 17 digits. The resulting string this morning was `20180727084011100`.

Is it possible that `L` gave `100` here because it ended with `00`? 

Either way, the expected behaviour is that `L` should always return two digits as the spec says. I'll change to use `l` for now.

**Comment by tossy310** [comment]
Hello!
I encountered the same problem and made PR for this issue in #88.

**Comment by jheander** [comment]
Fixed in fork [dateformat-light@1.2.1](https://www.npmjs.com/package/dateformat-light/v/1.2.1)

**Comment by traubad** [comment]
Pity the author never fixed this bug.
