### ISSUE TITLE
Issue when using 'date-format' or 'data-date-format' inside a <form> element

### ISSUE THREAD

**Issue by pjayme** [felixge/node-dateformat#90]
The incorrect date 'value' is being passed when a date-format other than its default format is specified. I can't quite understand the logic/outcome its producing but its producing a value that is at least 3+ years off the desired value.

**Comment by chase-manning** [comment]
Closing this issue as cannot replicate.  
@pjayme if you can still replicate please provide a more specific example and I can resolve.
