### ISSUE TITLE
Formating 'at' change to 'ap'

### ISSUE THREAD

**Issue by Eliaxs1900** [felixge/node-dateformat#94]
When i execute this console log:
`console.log('[Login] in ' + dateFormat(new Date(), 'dd-mm-yyyy at hh:mm:ss'));`
it return that:
`[Login] in 14-02-2019 ap 02:02:14`

see how change **at** by **ap**

**Comment by jheander** [comment]
You need to enclose `at` in quotes. Otherwise the 't' will be interpreted as am/pm short form.
```
console.log('[Login] in ' + dateFormat(new Date(), 'dd-mm-yyyy "at" hh:mm:ss'));
```

**Comment by Eliaxs1900** [comment]
Thanks
