### ISSUE TITLE
How to add it in an Angular Project Globally & Properly ?

### ISSUE THREAD

**Issue by garalimedkarim4** [felixge/node-dateformat#96]
Hi, I'm trying to add this package in my **Angular Project** But I didn't find how to this 
Can I do something in my **app.module.ts** file that let me use **dateFormat** in all my Project?

**Comment by chase-manning** [comment]
Hi @garalimedkarim4  sorry about the slow response here.  
You can add this using `npm i dateformat --save`.  
It will install it and add it to your `package.json` file so it will be saved.  
Will close this issue now but if you have any more issues or questions just let me know :smile:
