### ISSUE TITLE
React App breaks on IE pointing to dateformat.js

### ISSUE THREAD

**Issue by zlayabekrija** [felixge/node-dateformat#99]
Running of dateformat on IE from react app, breaks the app with error ```Exception thrown and not caught datefromat.js(36,1)

Do you have any solution workaround or anything that might help.

**Comment by chase-manning** [comment]
@zlayabekrija  This should be fixed now with the introduction of Babel to add more browser support.  
Can you please test this and raise another issue if it still exists?
